name: $(BuildDefinitionName)-$(date:yyMM).$(date:dd)$(rev:rrr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - latestw_all
pr:
  branches:
    include:
    - latestw_all

variables:
  vcpkgCacheDir: '$(Build.SourcesDirectory)/binary-cache'

stages:
- stage: BuildDependencies
  displayName: Build Dependencies
  jobs:
  - job: InstallDeps_x64
    displayName: Install vcpkg Dependencies (x64)
    pool:
      vmImage: windows-latest
    steps:
    - template: ./templates/install-vcpkg-dependencies.yml
      parameters:
        triplet: x64-custom
        artifactSuffix: x64
        vcpkgCacheDir: '$(vcpkgCacheDir)'

  - job: InstallDeps_x86
    displayName: Install vcpkg Dependencies (x86)
    pool:
      vmImage: windows-latest
    steps:
    - template: ./templates/install-vcpkg-dependencies.yml
      parameters:
        triplet: x86-custom
        artifactSuffix: x86
        vcpkgCacheDir: '$(vcpkgCacheDir)'

- stage: Build
  displayName: Build Win32-OpenSSH
  dependsOn: BuildDependencies
  jobs:
  - job: BuildPkg_x64
    displayName: Build Package (x64)
    pool:
      vmImage: windows-latest
    steps:
    - template: ./templates/build-win32-openssh-job.yml
      parameters:
        nativeHostArch: x64
        buildOutputDir: x64
        artifactSuffix: x64
        dependenciesArtifactName: vcpkg-dependencies-x64
        includeConfig: true
        vcpkgCacheDir: '$(vcpkgCacheDir)'

  - job: BuildPkg_x86
    displayName: Build Package (x86)
    pool:
      vmImage: windows-latest
    steps:
    - template: ./templates/build-win32-openssh-job.yml
      parameters:
        nativeHostArch: x86
        buildOutputDir: Win32
        artifactSuffix: x86
        dependenciesArtifactName: vcpkg-dependencies-x86
        vcpkgCacheDir: '$(vcpkgCacheDir)'

- stage: Test
  displayName: Test Win32-OpenSSH
  dependsOn: Build
  jobs:
  - job: TestPkgWin32OpenSSHCore
    pool:
      vmImage: windows-latest
    displayName: Win32-OpenSSH Core Tests On Windows
    variables:
      testFilesDrivePath: '**'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: current
        downloadType: single
        artifactName: Win32-OpenSSH-x64
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download unit test artifacts'
      inputs:
        buildType: current
        downloadType: single
        artifactName: UnitTests-x64
        downloadPath: '$(System.ArtifactsDirectory)'

    - pwsh: |
        $artifactDir = "$(System.ArtifactsDirectory)"
        Write-Verbose -Verbose -Message "Artifacts directory: $artifactDir"
        Get-ChildItem -Path $artifactDir -Recurse
      displayName: Capture downloaded artifact directory

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Install-OpenSSH -SourceDir "$(System.ArtifactsDirectory)/Win32-OpenSSH-x64/x64/Release" -OpenSSHDir "$env:SystemDrive/OpenSSH" -Verbose
      displayName: Install Win32-OpenSSH

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Install-UnitTests -SourceDir "$(System.ArtifactsDirectory)/UnitTests-x64/x64/Release" -OpenSSHDir "$env:SystemDrive/OpenSSH" -Verbose
      displayName: Install Unit Tests

    - pwsh: |
        $sourceDir = "$(Build.SourcesDirectory)"
        Write-Verbose -Verbose -Message "Source repo directory: $sourceDir"
        Get-ChildItem -Path $sourceDir
      displayName: Capture source repo directory for test

    - pwsh: |
        $installedOpenSSHDir = "$env:SystemDrive/OpenSSH"
        Write-Verbose -Verbose -Message "Installed OpenSSH directory: $installedOpenSSHDir"
        Get-ChildItem -Path $installedOpenSSHDir -Recurse
      displayName: Capture installed OpenSSH directory

    - pwsh: |
        # Run OpenSSH tests
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Invoke-OpenSSHTests -OpenSSHBinPath "$env:SystemDrive/OpenSSH"
      displayName: Run core tests

    - pwsh: |
        Write-Host "##vso[task.setvariable variable=testFilesDrivePath;]$env:SystemDrive"
      displayName: Set variable

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(testFilesDrivePath)/OpenSSHTests/*.xml'
        failTaskOnFailedTests: true
      condition: always()

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        #
        # Copy test results to results directory
        $ResultsDirectory = "$(Build.SourcesDirectory)/Win32OpenSSHTestResults"
        Copy-OpenSSHTestResults -ResultsPath $ResultsDirectory
        #
        # Upload test results artifact
        if (Test-Path -Path $ResultsDirectory)
        {
          $artifactName = 'Win32-OpenSSH-TestResults-Core'
          Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName;]$ResultsDirectory"
        }
      displayName: Upload test results
      condition: always()

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Clear-TestEnvironmentSetup
      displayName: Clean up OpenSSH test environment
      condition: always()

  - job: TestPkgWin32OpenSSHBash
    pool:
      vmImage: windows-latest
    displayName: Win32-OpenSSH Bash Tests On Windows
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: current
        downloadType: single
        artifactName: Win32-OpenSSH-x64
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download bash test config file artifact'
      inputs:
        buildType: current
        downloadType: single
        artifactName: ConfigFile-x64
        downloadPath: '$(System.ArtifactsDirectory)'

    - pwsh: |
        $artifactDir = "$(System.ArtifactsDirectory)"
        Write-Verbose -Verbose -Message "Artifacts directory: $artifactDir"
        Get-ChildItem -Path $artifactDir -Recurse
      displayName: Capture downloaded artifact directory

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Install-OpenSSH -SourceDir "$(System.ArtifactsDirectory)/Win32-OpenSSH-x64/x64/Release" -OpenSSHDir "$env:SystemDrive/OpenSSH" -Verbose
      displayName: Install Win32-OpenSSH

    - pwsh: |
        $configFileSrc = "$(System.ArtifactsDirectory)/ConfigFile-x64/config.h"
        $configFileDest = "$(Build.SourcesDirectory)"
        Write-Verbose -Verbose -Message "Copying config file from: ${configFileSrc} to: ${configFileDest}"
        Copy-Item -Path $configFileSrc -Dest $configFileDest -Force
      displayName: Copy config file artifact for bash tests

    - pwsh: |
        $sourceDir = "$(Build.SourcesDirectory)"
        Write-Verbose -Verbose -Message "Source repo directory: $sourceDir"
        Get-ChildItem -Path $sourceDir
      displayName: Capture source repo directory for test

    - pwsh: |
        $installedOpenSSHDir = "$env:SystemDrive/OpenSSH"
        Write-Verbose -Verbose -Message "Installed OpenSSH directory: $installedOpenSSHDir"
        Get-ChildItem -Path $installedOpenSSHDir -Recurse
      displayName: Capture installed OpenSSH directory

    - pwsh: |
        # Run OpenSSH bash tests
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Invoke-OpenSSHBashTestsOnly -OpenSSHBinPath "$env:SystemDrive/OpenSSH"
      displayName: Run bash tests

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        #
        # Copy test results to results directory
        $ResultsDirectory = "$(Build.SourcesDirectory)/Win32OpenSSHTestResults"
        Copy-OpenSSHTestResults -ResultsPath $ResultsDirectory
        #
        # Upload test results artifact
        if (Test-Path -Path $ResultsDirectory)
        {
          $artifactName = 'Win32-OpenSSH-TestResults-Bash'
          Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName;]$ResultsDirectory"
        }
      displayName: Upload test results
      condition: always()

    - pwsh: |
        Import-Module -Name "$(Build.SourcesDirectory)/contrib/win32/openssh/AzDOBuildTools" -Force
        Clear-TestEnvironmentSetup
      displayName: Clean up OpenSSH test environment
      condition: always()
